image: k33g/capsule-hello-universe:0.0.0
# Source code of the Dockerfile:
# See the docker directory of this project

tasks:
  - name: initialize
    before: |
      CAPSULE_VERSION="v0.2.3"
      OS="linux"
      ARCH="amd64"
      echo "💊 Installing the capsule launcher..."
      
      wget https://github.com/bots-garden/capsule/releases/\
      download/${CAPSULE_VERSION}/\
      capsule-${CAPSULE_VERSION}-${OS}-${ARCH}.tar.gz

      sudo tar -zxf \
      capsule-${CAPSULE_VERSION}-${OS}-${ARCH}.tar.gz \
      --directory /usr/local/bin

      rm capsule-${CAPSULE_VERSION}-${OS}-${ARCH}.tar.gz

    init: |
      echo "👋 Hello, Capsule is installed. Have fun 🙂"

ports:
  - port: 3000-25000
    visibility: public
    onOpen: ignore

vscode:
  extensions:
    - pkief.material-icon-theme
    - aaron-bond.better-comments
    - golang.go
    - PKief.material-icon-theme
